---
abstract: 'SQL query result set to XHTML table.'
author:
  - 'jeffa <info+cpan@unlocalhost.com>'
build_requires:
  DBI: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.130880'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-XHTML_Table
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.006
version: 1.45
